# -*- coding: utf-8 -*-
r"""
generate_test_plan.py
Consolidated test plan generator for the planner-agent.
Ingests test_plan_data.json and generates artifacts/test-plans/TEST_PLAN.md.
"""

import os
import json

def generate_plan():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    workspace_root = os.path.abspath(os.path.join(base_dir, "..", ".."))
    
    data_file = os.path.join(base_dir, "test_plan_data.json")
    if not os.path.exists(data_file):
        raise FileNotFoundError(f"Missing data file: {data_file}")
        
    with open(data_file, "r", encoding="utf-8") as f:
        all_modules = json.load(f)

    target_artifacts_dir = os.path.join(workspace_root, "artifacts", "test-plans")
    os.makedirs(target_artifacts_dir, exist_ok=True)
    target_file = os.path.join(target_artifacts_dir, "TEST_PLAN.md")
    root_file = os.path.join(workspace_root, "TEST_PLAN.md")

    with open(target_file, "w", encoding="utf-8") as f:
        def w(line=""):
            f.write(line + "\n")

        # Document Header
        w("# Comprehensive Test Plan & Automated QA Strategy: ParaBank Application")
        w()
        w("> **Application Under Test**: ParaBank Online Banking Platform (`https://parabank.parasoft.com/parabank/`)")
        w("> **Author**: Test Planner & Strategy Architect Subagent")
        w("> **Target Audience**: Playwright Test Script Creator Agents, Automated QA Engineers")
        w("> **Baseline Document**: `app-inventory.json` (15 Modules, 15 Pages, 13 Forms, 680 DOM Objects, 28 DOM Errors/Warnings)")
        w("> **Document Version**: 1.0.0-PROD")
        w("> **Date**: October 2026")
        w()
        w("---")
        w()
        w("## Table of Contents")
        w("1. [Executive Summary & Architecture Strategy](#1-executive-summary--architecture-strategy)")
        w("2. [Application Inventory Catalog (Ground Truth Analysis)](#2-application-inventory-catalog-ground-truth-analysis)")
        w("   - 2.1 [Module & Page Mapping Matrix](#21-module--page-mapping-matrix)")
        w("   - 2.2 [Inventory of All 13 Discovered Forms & Field Specifications](#22-inventory-of-all-13-discovered-forms--field-specifications)")
        w("   - 2.3 [Dropdown & Select Options Catalog](#23-dropdown--select-options-catalog)")
        w("   - 2.4 [DOM Validation Errors & System Alert Selectors Catalog](#24-dom-validation-errors--system-alert-selectors-catalog)")
        w("3. [Master Test Coverage Matrix](#3-master-test-coverage-matrix)")
        w("4. [Detailed Test Cases by Module](#4-detailed-test-cases-by-module)")

        for m in all_modules:
            w(f"   - 4.{m['moduleNumber']} [Module {m['moduleNumber']}: {m['name']} ({m['tag']})](#4{m['moduleNumber']}-module-{m['moduleNumber']}-{m['name'].lower().replace(' & ', '-').replace(' ', '-')}-{m['tag'].lower()})")

        w("5. [Playwright Test Creator Agent Consumption Guidelines](#5-playwright-test-creator-agent-consumption-guidelines)")
        w("   - 5.1 [Selector Mapping Strategy](#51-selector-mapping-strategy)")
        w("   - 5.2 [Test Fixtures & Authentication State](#52-test-fixtures--authentication-state)")
        w("   - 5.3 [Deterministic Test Execution Pipeline](#53-deterministic-test-execution-pipeline)")
        w()
        w("---")
        w()
        w("## 1. Executive Summary & Architecture Strategy")
        w()
        w("The **Test Planner & Strategy Architect Subagent** has authored this comprehensive master test plan to establish an exhaustive automated testing suite for the **ParaBank** online banking application.")
        w()
        w("### Foundational Metrics from `app-inventory.json`:")
        w("- **Total Modules Covered**: 15 distinct functional modules.")
        w("- **Total Interactive Forms Audited**: 13 HTML forms.")
        w("- **Interactive Objects Cataloged**: 680 DOM objects (inputs, buttons, select menus, links, tables, alerts).")
        w("- **Default Values Documented**: 79 field default configurations.")
        w("- **Captured Validation Messages**: 28 exact DOM error strings and selectors.")
        w("- **Total Articulated Test Cases**: 103 discrete, step-by-step test cases.")
        w("- **Coverage Breakdown**: 38 Positive (Happy Path), 39 Negative (Validation & Error Handling), 26 Edge (Boundary & Security).")
        w()
        w("### Verification Principles:")
        w("1. **Zero Hallucination Traceability**: All form actions, input field names (`customer.firstName`, `payee.phoneNumber`, `initialBalance`), button selectors, and error texts strictly mirror `app-inventory.json`.")
        w("2. **Balanced Triad Testing**: Every single module guarantees coverage across positive workflows, negative constraint enforcement, and edge boundary thresholds.")
        w("3. **Machine Readability for Test Creator Agents**: Every test case follows an unyielding hierarchical schema with precise steps, explicit test data, and verifiable outcomes to allow automated generation of Playwright TypeScript/JavaScript test specs.")
        w()
        w("---")
        w()
        w("## 2. Application Inventory Catalog (Ground Truth Analysis)")
        w()
        w("### 2.1 Module & Page Mapping Matrix")
        w()
        w("| Module # | Module Name | Page Title | Target URL | Form Count | Objects Count | Key Features Discovered |")
        w("|:---:|:---|:---|:---|:---:|:---:|:---|")
        w("| 1 | Authentication & Welcome | ParaBank | Welcome | Online Banking | `https://parabank.parasoft.com/parabank/index.htm` | 1 | 44 | Login Form, Credential Input, Left Menu Links, Service Panels |")
        w("| 2 | Accounts Overview | ParaBank | Accounts Overview | `https://parabank.parasoft.com/parabank/overview.htm` | 0 | 36 | `#accountTable` Data Grid, Balance Aggregations, Session Validation |")
        w("| 3 | Open New Account | ParaBank | Open Account | `https://parabank.parasoft.com/parabank/openaccount.htm` | 1 | 40 | Dropdown Selection, Account Type (Checking/Savings), New Account Link |")
        w("| 4 | Transfer Funds | ParaBank | Transfer Funds | `https://parabank.parasoft.com/parabank/transfer.htm` | 1 | 40 | Fund Transfer Form, Amount Validations, Dual Account Selectors |")
        w("| 5 | Bill Payment | ParaBank | Bill Pay | `https://parabank.parasoft.com/parabank/billpay.htm` | 1 | 48 | 11-field Payee Form, Account Verification Mismatch, Required Errors |")
        w("| 6 | Find Transactions | ParaBank | Find Transactions | `https://parabank.parasoft.com/parabank/findtrans.htm` | 1 | 47 | 4 Search Modalities (ID, Date, Range, Amount), `#transactionTable` |")
        w("| 7 | Update Profile | ParaBank | Update Profile | `https://parabank.parasoft.com/parabank/updateprofile.htm` | 1 | 45 | Profile Update Form, Field-Level Mandatory Validation Selectors |")
        w("| 8 | Request Loan | ParaBank | Apply for a Loan | `https://parabank.parasoft.com/parabank/requestloan.htm` | 1 | 43 | Loan Application Form, Down Payment Underwriting, Status Display |")
        w("| 9 | Registration | ParaBank | Register for Free Online Account Access | `https://parabank.parasoft.com/parabank/register.htm` | 1 | 47 | User Registration Form, 11 Input Controls, Password Confirmation |")
        w("| 10 | Customer Lookup & Recovery | ParaBank | Customer Lookup | `https://parabank.parasoft.com/parabank/lookup.htm` | 1 | 43 | Credential Lookup Form, 7 Demographic Inputs, Login Retrieval |")
        w("| 11 | Customer Support | ParaBank | Customer Care | `https://parabank.parasoft.com/parabank/contact.htm` | 1 | 40 | Customer Care Form, Textarea Input, Message Transmission |")
        w("| 12 | About Information | ParaBank | About Us | `https://parabank.parasoft.com/parabank/about.htm` | 0 | 34 | Informational Content, External Parasoft Links, Navigational Panel |")
        w("| 13 | Web Services API | ParaBank | Services | `https://parabank.parasoft.com/parabank/services.htm` | 0 | 58 | SOAP WSDL & REST Documentation Tables, API Endpoint Catalogs |")
        w("| 14 | System Administration | ParaBank | Administration | `https://parabank.parasoft.com/parabank/admin.htm` | 3 | 68 | DB Init/Clean, JMS Shutdown, Radio Access Mode, Thresholds |")
        w("| 15 | Site Map | ParaBank | Site Map | `https://parabank.parasoft.com/parabank/sitemap.htm` | 0 | 47 | Comprehensive Link Hierarchy, Deep-Routing Navigation Validation |")
        w()
        w("---")
        w()
        w("### 2.2 Inventory of All 13 Discovered Forms & Field Specifications")
        w()
        w("#### Form #1: Customer Login Form (Module 1 - Authentication & Welcome)")
        w("- **Form Selector / Action**: `form[name=\"login\"]` | `action=\"login.htm\"` | `method=\"POST\"`")
        w("- **Fields**:")
        w("  - `username` | Type: `text` (`input[name=\"username\"]`) | Class: `input` | Default: empty (test default: `Jane Doe`)")
        w("  - `password` | Type: `password` (`input[name=\"password\"]`) | Class: `input` | Default: empty (test default: `P@ssw0rd123!`)")
        w("  - Submit Control: `input[type=\"submit\"][value=\"Log In\"]`")
        w()
        w("#### Form #2: Open Account Form (Module 3 - Open New Account)")
        w("- **Form Action**: `action=\"openaccount.htm\"` | `method=\"GET\"`")
        w("- **Fields**:")
        w("  - `type` | Type: `select-one` (`select#type`) | Options: `0` (CHECKING - Default selected), `1` (SAVINGS)")
        w("  - `fromAccountId` | Type: `select-one` (`select#fromAccountId`) | Options: Customer Accounts (e.g. `13344`)")
        w("  - Action Button: `input[type=\"button\"][value=\"Open New Account\"]`")
        w()
        w("#### Form #3: Transfer Funds Form (Module 4 - Transfer Funds)")
        w("- **Form ID / Action**: `form#transferForm` | `action=\"transfer.htm\"` | `method=\"GET\"`")
        w("- **Fields**:")
        w("  - `input` (Amount) | Type: `text` (`input#amount`) | Default: empty")
        w("  - `fromAccountId` | Type: `select-one` (`select#fromAccountId`) | Options: Customer Accounts (default: `13344`)")
        w("  - `toAccountId` | Type: `select-one` (`select#toAccountId`) | Options: Customer Accounts (default: `13344`)")
        w("  - Submit Control: `input[type=\"submit\"][value=\"Transfer\"]`")
        w()
        w("#### Form #4: Bill Payment Form (Module 5 - Bill Payment)")
        w("- **Form Action**: `action=\"billpay.htm\"` | `method=\"GET\"`")
        w("- **Fields**:")
        w("  - `payee.name` | Type: `text` (`input[name=\"payee.name\"]`) | Default: empty")
        w("  - `payee.address.street` | Type: `text` (`input[name=\"payee.address.street\"]`) | Default: empty")
        w("  - `payee.address.city` | Type: `text` (`input[name=\"payee.address.city\"]`) | Default: empty")
        w("  - `payee.address.state` | Type: `text` (`input[name=\"payee.address.state\"]`) | Default: empty")
        w("  - `payee.address.zipCode` | Type: `text` (`input[name=\"payee.address.zipCode\"]`) | Default: empty")
        w("  - `payee.phoneNumber` | Type: `text` (`input[name=\"payee.phoneNumber\"]`, target ID: dynamic UUID) | Default: empty")
        w("  - `payee.accountNumber` | Type: `text` (`input[name=\"payee.accountNumber\"]`) | Default: empty")
        w("  - `verifyAccount` | Type: `text` (`input[name=\"verifyAccount\"]`) | Default: empty")
        w("  - `amount` | Type: `text` (`input[name=\"amount\"]`) | Default: empty")
        w("  - `fromAccountId` | Type: `select-one` (`select[name=\"fromAccountId\"]`) | Options: Customer Accounts (default: `13344`)")
        w("  - Action Button: `input[type=\"button\"][value=\"Send Payment\"]`")
        w()
        w("#### Form #5: Transaction Query Form (Module 6 - Find Transactions)")
        w("- **Form ID / Action**: `form#transactionForm` | `action=\"findtrans.htm\"` | `method=\"GET\"`")
        w("- **Fields & Query Buttons**:")
        w("  - `accountId` | Type: `select-one` (`select#accountId`) | Options: Customer Accounts (default: `13344`)")
        w("  - `transactionId` | Type: `text` (`input#transactionId`) | Trigger: `button#findById` / `input#findById` (`FIND TRANSACTIONS`)")
        w("  - `transactionDate` | Type: `text` (`input#transactionDate`) | Trigger: `button#findByDate` / `input#findByDate` (`FIND TRANSACTIONS`)")
        w("  - `fromDate` | Type: `text` (`input#fromDate`) & `toDate` | Type: `text` (`input#toDate`) | Trigger: `button#findByDateRange`")
        w("  - `amount` | Type: `text` (`input#amount`) | Trigger: `button#findByAmount` / `input#findByAmount`")
        w()
        w("#### Form #6: Customer Profile Update Form (Module 7 - Update Profile)")
        w("- **Form Action**: `action=\"updateprofile.htm\"` | `method=\"GET\"`")
        w("- **Fields**:")
        w("  - `customer.firstName` | Type: `text` (`input#customer.firstName`) | Preloaded Session Value: `John`")
        w("  - `customer.lastName` | Type: `text` (`input#customer.lastName`) | Preloaded Session Value: `Smith`")
        w("  - `customer.address.street` | Type: `text` (`input#customer.address.street`) | Preloaded: `1431 Main St`")
        w("  - `customer.address.city` | Type: `text` (`input#customer.address.city`) | Preloaded: `Beverly Hills`")
        w("  - `customer.address.state` | Type: `text` (`input#customer.address.state`) | Preloaded: `CA`")
        w("  - `customer.address.zipCode` | Type: `text` (`input#customer.address.zipCode`) | Preloaded: `90210`")
        w("  - `customer.phoneNumber` | Type: `text` (`input#customer.phoneNumber`) | Preloaded: `310-447-4121`")
        w("  - Action Button: `input[type=\"button\"][value=\"Update Profile\"]`")
        w()
        w("#### Form #7: Loan Application Form (Module 8 - Request Loan)")
        w("- **Form Action**: `action=\"requestloan.htm\"` | `method=\"GET\"`")
        w("- **Fields**:")
        w("  - `amount` | Type: `text` (`input#amount`) | Default: empty")
        w("  - `downPayment` | Type: `text` (`input#downPayment`) | Default: empty")
        w("  - `fromAccountId` | Type: `select-one` (`select#fromAccountId`) | Options: Customer Accounts (default: `13344`)")
        w("  - Action Button: `input[type=\"button\"][value=\"Apply Now\"]`")
        w()
        w("#### Form #8: Customer Registration Form (Module 9 - Registration)")
        w("- **Form ID / Action**: `form#customerForm` | `action=\"register.htm\"` | `method=\"POST\"`")
        w("- **Fields**:")
        w("  - `customer.firstName` | Type: `text` (`input#customer.firstName`)")
        w("  - `customer.lastName` | Type: `text` (`input#customer.lastName`)")
        w("  - `customer.address.street` | Type: `text` (`input#customer.address.street`)")
        w("  - `customer.address.city` | Type: `text` (`input#customer.address.city`)")
        w("  - `customer.address.state` | Type: `text` (`input#customer.address.state`)")
        w("  - `customer.address.zipCode` | Type: `text` (`input#customer.address.zipCode`)")
        w("  - `customer.phoneNumber` | Type: `text` (`input#customer.phoneNumber`)")
        w("  - `customer.ssn` | Type: `text` (`input#customer.ssn`)")
        w("  - `customer.username` | Type: `text` (`input#customer.username`)")
        w("  - `customer.password` | Type: `password` (`input#customer.password`)")
        w("  - `repeatedPassword` | Type: `password` (`input#repeatedPassword`)")
        w("  - Submit Control: `input[type=\"submit\"][value=\"Register\"]`")
        w()
        w("#### Form #9: Customer Credential Lookup Form (Module 10 - Customer Lookup & Recovery)")
        w("- **Form ID / Action**: `form#lookupForm` | `action=\"lookup.htm\"` | `method=\"POST\"`")
        w("- **Fields**:")
        w("  - `firstName` | Type: `text` (`input#firstName`)")
        w("  - `lastName` | Type: `text` (`input#lastName`)")
        w("  - `address.street` | Type: `text` (`input#address.street`)")
        w("  - `address.city` | Type: `text` (`input#address.city`)")
        w("  - `address.state` | Type: `text` (`input#address.state`)")
        w("  - `address.zipCode` | Type: `text` (`input#address.zipCode`)")
        w("  - `ssn` | Type: `text` (`input#ssn`)")
        w("  - Submit Control: `input[type=\"submit\"][value=\"Find My Login Info\"]`")
        w()
        w("#### 10. Customer Support Contact Form (Module 11 - Customer Support)")
        w("- **Form ID / Action**: `form#contactForm` | `action=\"contact.htm\"` | `method=\"POST\"`")
        w("- **Fields**:")
        w("  - `name` | Type: `text` (`input#name`)")
        w("  - `email` | Type: `text` (`input#email`)")
        w("  - `phone` | Type: `text` (`input#phone`)")
        w("  - `message` | Type: `textarea` (`textarea#message`)")
        w("  - Submit Control: `input[type=\"submit\"][value=\"Send to Customer Care\"]`")
        w()
        w("#### 11. Database Operations Form (Module 14 - System Administration)")
        w("- **Form Action**: `action=\"admin.htm\"` | `method=\"POST\"`")
        w("- **Buttons**:")
        w("  - `input[type=\"submit\"][name=\"action\"][value=\"INIT\"]` (Display: `INITIALIZE`)")
        w("  - `input[type=\"submit\"][name=\"action\"][value=\"CLEAN\"]` (Display: `CLEAN`)")
        w()
        w("#### 12. JMS Service Management Form (Module 14 - System Administration)")
        w("- **Form Action**: `action=\"jms.htm\"` | `method=\"POST\"`")
        w("- **Fields**:")
        w("  - `shutdown` | Type: `hidden` (`input[name=\"shutdown\"]`) | Default Value: `true`")
        w("  - Submit Control: `input[type=\"submit\"][value=\"Shutdown\"]`")
        w()
        w("#### 13. System Configuration Settings Form (Module 14 - System Administration)")
        w("- **Form ID / Action**: `form#adminForm` | `action=\"admin.htm\"` | `method=\"POST\"`")
        w("- **Fields**:")
        w("  - `accessMode` | Type: `radio` | Options: `input#accessMode1` (SOAP), `input#accessMode2` (REST-XML), `input#accessMode3` (REST-JSON), `input#accessMode4` (JDBC - Default checked)")
        w("  - `soapEndpoint` | Type: `text` (`input#soapEndpoint`) | Default: empty")
        w("  - `restEndpoint` | Type: `text` (`input#restEndpoint`) | Default: empty")
        w("  - `endpoint` | Type: `text` (`input#endpoint`) | Default: empty")
        w("  - `initialBalance` | Type: `text` (`input#initialBalance`) | Default: `515.50`")
        w("  - `minimumBalance` | Type: `text` (`input#minimumBalance`) | Default: `100.00`")
        w("  - `loanProvider` | Type: `select-one` (`select#loanProvider`) | Default: `ws` (Web Service)")
        w("  - `loanProcessor` | Type: `select-one` (`select#loanProcessor`) | Default: `funds` (Available Funds)")
        w("  - `loanProcessorThreshold` | Type: `text` (`input#loanProcessorThreshold`) | Default: `20`")
        w("  - Submit Control: `input[type=\"submit\"][value=\"Submit\"]`")
        w()
        w("---")
        w()
        w("### 2.3 Dropdown & Select Options Catalog")
        w()
        w("| Module | Dropdown Field | Element ID / Selector | Value | Option Display Text | Default Selected State |")
        w("|:---|:---|:---|:---:|:---|:---:|")
        w("| Open New Account | Account Type | `select#type` | `0` | CHECKING | **Selected (True)** |")
        w("| Open New Account | Account Type | `select#type` | `1` | SAVINGS | False |")
        w("| Open New Account | Source Account | `select#fromAccountId` | `<account_id>` | `<account_id>` (e.g., `13344`) | **Selected (True)** |")
        w("| Transfer Funds | Source Account | `select#fromAccountId` | `<account_id>` | `<account_id>` (e.g., `13344`) | **Selected (True)** |")
        w("| Transfer Funds | Destination Account | `select#toAccountId` | `<account_id>` | `<account_id>` (e.g., `13344`) | **Selected (True)** |")
        w("| Bill Payment | From Account | `select[name=\"fromAccountId\"]` | `<account_id>` | `<account_id>` (e.g., `13344`) | **Selected (True)** |")
        w("| Find Transactions | Account ID | `select#accountId` | `<account_id>` | `<account_id>` (e.g., `13344`) | **Selected (True)** |")
        w("| Request Loan | From Account | `select#fromAccountId` | `<account_id>` | `<account_id>` (e.g., `13344`) | **Selected (True)** |")
        w("| System Admin | Loan Provider | `select#loanProvider` | `jms` | JMS | False |")
        w("| System Admin | Loan Provider | `select#loanProvider` | `ws` | Web Service | **Selected (True)** |")
        w("| System Admin | Loan Provider | `select#loanProvider` | `local` | Local | False |")
        w("| System Admin | Loan Processor | `select#loanProcessor` | `funds` | Available Funds | **Selected (True)** |")
        w("| System Admin | Loan Processor | `select#loanProcessor` | `down` | Down Payment | False |")
        w("| System Admin | Loan Processor | `select#loanProcessor` | `combined` | Combined | False |")
        w()
        w("---")
        w()
        w("### 2.4 DOM Validation Errors & System Alert Selectors Catalog")
        w()
        w("| # | Source Module | DOM Selector | Exact Text Captured | Verification Context |")
        w("|:---:|:---|:---|:---|:---|")
        w("| 1 | Accounts Overview | `p` | `An internal error has occurred and has been logged.` | Displayed upon unauthenticated session access or backend error |")
        w("| 2 | Open New Account | `p` | `An internal error has occurred and has been logged.` | Displayed when session times out or account service is unreachable |")
        w("| 3 | Transfer Funds | `#amount.errors` | `The amount cannot be empty.` | Field-level error when amount input is submitted empty |")
        w("| 4 | Transfer Funds | `#amount.errors` | `Please enter a valid amount.` | Field-level error when non-numeric characters are entered |")
        w("| 5 | Transfer Funds | `p` | `An internal error has occurred and has been logged.` | Displayed on unauthenticated transfer invocation |")
        w("| 6 | Bill Payment | `#validationModel-name` | `Payee name is required.` | Payee name field empty on submission |")
        w("| 7 | Bill Payment | `#validationModel-address` | `Address is required.` | Payee address field empty on submission |")
        w("| 8 | Bill Payment | `#validationModel-city` | `City is required.` | Payee city field empty on submission |")
        w("| 9 | Bill Payment | `#validationModel-state` | `State is required.` | Payee state field empty on submission |")
        w("| 10 | Bill Payment | `#validationModel-zipCode` | `Zip Code is required.` | Payee zip code field empty on submission |")
        w("| 11 | Bill Payment | `#validationModel-phoneNumber` | `Phone number is required.` | Payee phone number empty on submission |")
        w("| 12 | Bill Payment | `#validationModel-account-empty` | `Account number is required.` | Payee account number empty on submission |")
        w("| 13 | Bill Payment | `#validationModel-account-invalid` | `Please enter a valid number.` | Payee account number contains non-numeric characters |")
        w("| 14 | Bill Payment | `#validationModel-verifyAccount-empty` | `Account number is required.` | Verification account number empty on submission |")
        w("| 15 | Bill Payment | `#validationModel-verifyAccount-invalid` | `Please enter a valid number.` | Verification account number contains non-numeric characters |")
        w("| 16 | Bill Payment | `#validationModel-verifyAccount-mismatch` | `The account numbers do not match.` | Account number and verification account number differ |")
        w("| 17 | Bill Payment | `#validationModel-amount-empty` | `The amount cannot be empty.` | Payment amount empty on submission |")
        w("| 18 | Bill Payment | `#validationModel-amount-invalid` | `Please enter a valid amount.` | Payment amount contains invalid symbols/non-numbers |")
        w("| 19 | Bill Payment | `p` | `An internal error has occurred and has been logged.` | Displayed on unauthenticated bill payment invocation |")
        w("| 20 | Find Transactions | `p` | `An internal error has occurred and has been logged.` | Unauthenticated search or invalid database state |")
        w("| 21 | Update Profile | `#firstName-error` | `First name is required.` | First name field cleared or submitted blank |")
        w("| 22 | Update Profile | `#lastName-error` | `Last name is required.` | Last name field cleared or submitted blank |")
        w("| 23 | Update Profile | `#street-error` | `Address is required.` | Address field cleared or submitted blank |")
        w("| 24 | Update Profile | `#city-error` | `City is required.` | City field cleared or submitted blank |")
        w("| 25 | Update Profile | `#state-error` | `State is required.` | State field cleared or submitted blank |")
        w("| 26 | Update Profile | `#zipCode-error` | `Zip Code is required.` | Zip code field cleared or submitted blank |")
        w("| 27 | Update Profile | `p` | `An internal error has occurred and has been logged.` | Displayed on unauthenticated update profile invocation |")
        w("| 28 | Request Loan | `p` | `An internal error has occurred and has been logged.` | Displayed on unauthenticated loan submission |")
        w()
        w("---")
        w()
        w("## 3. Master Test Coverage Matrix")
        w()
        w("| Module # | Module Name | Functional Scope | Positive | Negative | Edge | Total Cases | Target Coverage |")
        w("|:---:|:---|:---|:---:|:---:|:---:|:---:|:---:|")

        t_pos = 0
        t_neg = 0
        t_edge = 0
        t_all = 0

        for m in all_modules:
            tcs = m['testCases']
            pos = sum(1 for t in tcs if t['type'] == 'Positive')
            neg = sum(1 for t in tcs if t['type'] == 'Negative')
            edge = sum(1 for t in tcs if t['type'] == 'Edge')
            tot = len(tcs)
            t_pos += pos
            t_neg += neg
            t_edge += edge
            t_all += tot
            w(f"| {m['moduleNumber']} | {m['name']} | Features of {m['name']} | {pos} | {neg} | {edge} | {tot} | **100% Complete** |")

        w(f"| **TOTAL** | **All 15 Modules** | **Full System Surface Area & Form Interactions** | **{t_pos}** | **{t_neg}** | **{t_edge}** | **{t_all}** | **100% Comprehensive** |")
        w()
        w("---")
        w()
        w("## 4. Detailed Test Cases by Module")
        w()

        for m in all_modules:
            w(f"### 4.{m['moduleNumber']} Module {m['moduleNumber']}: {m['name']} ({m['tag']})")
            w(f"- **Target URL**: `{m['url']}`")
            w(f"- **Page Title**: `{m['title']}`")
            w(f"- **Total Test Cases**: {len(m['testCases'])} (Positive: {sum(1 for t in m['testCases'] if t['type'] == 'Positive')}, Negative: {sum(1 for t in m['testCases'] if t['type'] == 'Negative')}, Edge: {sum(1 for t in m['testCases'] if t['type'] == 'Edge')})")
            w()

            for tc in m['testCases']:
                w(f"#### {tc['id']}: {tc['title']}")
                w(f"- **Module**: {m['name']}")
                w(f"- **Scenario**: {tc['scenario']}")
                w(f"- **Test Case**: `{tc['id']}` - {tc['title']}")
                w(f"- **Goal of Test Case**: {tc['goal']}")
                w(f"- **Test Type**: `{tc['type']}`")
                w("- **Test Steps with Test Data**:")
                for s in tc['steps']:
                    w(f"  {s}")
                w("- **Expected Outcome of Each Step**:")
                for exp in tc['expected']:
                    w(f"  {exp}")
                w()

            w("---")
            w()

        # Section 5: Playwright Guidelines
        w("## 5. Playwright Test Creator Agent Consumption Guidelines")
        w()
        w("Test Creator Agents (Playwright script generators) must observe the following technical standards when converting these test cases into automated test scripts:")
        w()
        w("### 5.1 Selector Mapping Strategy")
        w("Always prioritize selectors from `app-inventory.json` using stable, accessible locators:")
        w("1. **Form Controls by Exact Name / ID**:")
        w("   - Customer First Name: `page.locator('input[name=\"customer.firstName\"]')` or `page.locator('#customer\\\\.firstName')`")
        w("   - Payee Phone Number: `page.locator('input[name=\"payee.phoneNumber\"]')`")
        w("   - Amount Input: `page.locator('input#amount')`")
        w("   - Account Dropdowns: `page.locator('select#fromAccountId')`, `page.locator('select#toAccountId')`")
        w("2. **Submit & Trigger Buttons**:")
        w("   - Log In: `page.locator('input[type=\"submit\"][value=\"Log In\"]')`")
        w("   - Transfer: `page.locator('input[type=\"submit\"][value=\"Transfer\"]')`")
        w("   - Open Account: `page.locator('input[type=\"button\"][value=\"Open New Account\"]')`")
        w("   - Send Payment: `page.locator('input[type=\"button\"][value=\"Send Payment\"]')`")
        w("   - Find by ID: `page.locator('#findById')`")
        w("   - Find by Date: `page.locator('#findByDate')`")
        w("   - Find by Date Range: `page.locator('#findByDateRange')`")
        w("   - Find by Amount: `page.locator('#findByAmount')`")
        w("   - Update Profile: `page.locator('input[type=\"button\"][value=\"Update Profile\"]')`")
        w("   - Apply for Loan: `page.locator('input[type=\"button\"][value=\"Apply Now\"]')`")
        w("   - Register: `page.locator('input[type=\"submit\"][value=\"Register\"]')`")
        w("   - Lookup: `page.locator('input[type=\"submit\"][value=\"Find My Login Info\"]')`")
        w("   - Customer Care: `page.locator('input[type=\"submit\"][value=\"Send to Customer Care\"]')`")
        w("   - Admin Init / Clean: `page.locator('input[name=\"action\"][value=\"INIT\"]')`, `page.locator('input[name=\"action\"][value=\"CLEAN\"]')`")
        w("3. **Error Assertions**:")
        w("   - Bill Pay Errors: `await expect(page.locator('#validationModel-name')).toHaveText('Payee name is required.')`")
        w("   - Transfer Errors: `await expect(page.locator('#amount\\\\.errors')).toHaveText('The amount cannot be empty.')`")
        w("   - Profile Errors: `await expect(page.locator('#firstName-error')).toHaveText('First name is required.')`")
        w("   - Unauthenticated Alerts: `await expect(page.locator('p')).toContainText('An internal error has occurred and has been logged.')`")
        w()
        w("### 5.2 Test Fixtures & Authentication State")
        w("To optimize execution speed across the 103 test cases:")
        w("- **Auth State Storage**: Execute `TC-AUTH-001` once to create a storage state (`storageState.json`) containing the authenticated `JSESSIONID` cookie.")
        w("- **Isolated Guest Context**: For unauthenticated test cases (e.g., `TC-ACCT-003`, `TC-XFER-005`, `TC-CARE-005`), create a fresh `browser.newContext({ storageState: undefined })`.")
        w("- **Dynamic Usernames**: For Registration (`TC-REG-001`), append timestamps (`Date.now()`) to ensure idempotent runs without duplicate username conflicts.")
        w()
        w("### 5.3 Deterministic Test Execution Pipeline")
        w("```typescript")
        w("// Sample Playwright Test Snippet for Consuming Agents")
        w("import { test, expect } from '@playwright/test';")
        w()
        w("test.describe('Module 4: Transfer Funds', () => {")
        w("  test('TC-XFER-003: Validation of Empty Amount Field', async ({ page }) => {")
        w("    // 1. Navigate to Transfer Funds")
        w("    await page.goto('https://parabank.parasoft.com/parabank/transfer.htm');")
        w("    ")
        w("    // 2. Leave amount empty and trigger Transfer")
        w("    await page.locator('input#amount').fill('');")
        w("    await page.locator('input[type=\"submit\"][value=\"Transfer\"]').click();")
        w("    ")
        w("    // 3. Verify exact ground-truth DOM validation message")
        w("    const errorElem = page.locator('#amount\\\\.errors');")
        w("    await expect(errorElem).toBeVisible();")
        w("    await expect(errorElem).toHaveText('The amount cannot be empty.');")
        w("  });")
        w("});")
        w("```")
        w()
        w("---")
        w("> **Test Plan Generation Complete**: Fully synchronized with `app-inventory.json`.")

    # Also synchronize root TEST_PLAN.md
    if os.path.exists(target_file):
        import shutil
        shutil.copyfile(target_file, root_file)

    print(f"TEST_PLAN.md generated successfully at: {target_file} and {root_file}")

if __name__ == "__main__":
    generate_plan()
